// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.sigin.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_35b83964f2ce68db, []int{0}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Expires              string   `protobuf:"bytes,2,opt,name=expires,proto3" json:"expires,omitempty"`
	Status               bool     `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_35b83964f2ce68db, []int{1}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthResponse) GetExpires() string {
	if m != nil {
		return m.Expires
	}
	return ""
}

func (m *AuthResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*AuthRequest)(nil), "proto.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "proto.AuthResponse")
}

func init() {
	proto.RegisterFile("service.sigin.proto", fileDescriptor_35b83964f2ce68db)
}

var fileDescriptor_35b83964f2ce68db = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8e, 0xc1, 0x6e, 0x82, 0x40,
	0x10, 0x86, 0x43, 0x5b, 0x28, 0x9d, 0x72, 0x1a, 0x9a, 0x66, 0xc3, 0x89, 0x70, 0xe2, 0x44, 0x93,
	0xfa, 0x00, 0xc4, 0x57, 0x80, 0xc4, 0x3b, 0xea, 0x44, 0x37, 0x2a, 0xbb, 0xee, 0x2c, 0xea, 0xe3,
	0x1b, 0x76, 0xc1, 0xe8, 0x69, 0xf3, 0xfd, 0x9b, 0x7c, 0xf3, 0x41, 0xca, 0x64, 0x2e, 0x72, 0x43,
	0x15, 0xcb, 0x9d, 0xec, 0x2b, 0x6d, 0x94, 0x55, 0x18, 0xba, 0xa7, 0xa8, 0xe1, 0x7b, 0x39, 0xd8,
	0x7d, 0x43, 0xe7, 0x81, 0xd8, 0xe2, 0x0f, 0x84, 0x74, 0xea, 0xe4, 0x51, 0x04, 0x79, 0x50, 0x7e,
	0x35, 0x1e, 0x30, 0x83, 0x58, 0x77, 0xcc, 0x57, 0x65, 0xb6, 0xe2, 0xcd, 0x7d, 0x3c, 0xb8, 0x58,
	0x41, 0xe2, 0x05, 0xac, 0x55, 0xcf, 0x34, 0x1a, 0xac, 0x3a, 0x50, 0x3f, 0x1b, 0x1c, 0xa0, 0x80,
	0x4f, 0xba, 0x69, 0x69, 0x88, 0x27, 0xc1, 0x8c, 0xf8, 0x0b, 0x11, 0xdb, 0xce, 0x0e, 0x2c, 0xde,
	0xf3, 0xa0, 0x8c, 0x9b, 0x89, 0xfe, 0x6b, 0x48, 0xda, 0x31, 0xb7, 0xf5, 0xed, 0xf8, 0x07, 0x1f,
	0xe3, 0x1d, 0x44, 0xdf, 0x5f, 0x3d, 0x55, 0x67, 0xe9, 0xcb, 0xe6, 0x43, 0xd6, 0x91, 0xdb, 0x16,
	0xf7, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf9, 0xa4, 0x86, 0x32, 0xfe, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SiginServiceClient is the client API for SiginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SiginServiceClient interface {
	Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
}

type siginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSiginServiceClient(cc grpc.ClientConnInterface) SiginServiceClient {
	return &siginServiceClient{cc}
}

func (c *siginServiceClient) Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/proto.SiginService/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SiginServiceServer is the server API for SiginService service.
type SiginServiceServer interface {
	Auth(context.Context, *AuthRequest) (*AuthResponse, error)
}

// UnimplementedSiginServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSiginServiceServer struct {
}

func (*UnimplementedSiginServiceServer) Auth(ctx context.Context, req *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
}

func RegisterSiginServiceServer(s *grpc.Server, srv SiginServiceServer) {
	s.RegisterService(&_SiginService_serviceDesc, srv)
}

func _SiginService_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiginServiceServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SiginService/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiginServiceServer).Auth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SiginService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SiginService",
	HandlerType: (*SiginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _SiginService_Auth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.sigin.proto",
}
