// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.phone.confirmation.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PhoneConfirmRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Sign                 string   `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign,omitempty"`
	Channel              string   `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	CallbackUrl          string   `protobuf:"bytes,5,opt,name=callbackUrl,proto3" json:"callbackUrl,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhoneConfirmRequest) Reset()         { *m = PhoneConfirmRequest{} }
func (m *PhoneConfirmRequest) String() string { return proto.CompactTextString(m) }
func (*PhoneConfirmRequest) ProtoMessage()    {}
func (*PhoneConfirmRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52e9aa8bf733a4d2, []int{0}
}

func (m *PhoneConfirmRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneConfirmRequest.Unmarshal(m, b)
}
func (m *PhoneConfirmRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneConfirmRequest.Marshal(b, m, deterministic)
}
func (m *PhoneConfirmRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneConfirmRequest.Merge(m, src)
}
func (m *PhoneConfirmRequest) XXX_Size() int {
	return xxx_messageInfo_PhoneConfirmRequest.Size(m)
}
func (m *PhoneConfirmRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneConfirmRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneConfirmRequest proto.InternalMessageInfo

func (m *PhoneConfirmRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *PhoneConfirmRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *PhoneConfirmRequest) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *PhoneConfirmRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *PhoneConfirmRequest) GetCallbackUrl() string {
	if m != nil {
		return m.CallbackUrl
	}
	return ""
}

func (m *PhoneConfirmRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type PhoneConfirmResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ExtendStatus         string   `protobuf:"bytes,2,opt,name=extendStatus,proto3" json:"extendStatus,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhoneConfirmResponse) Reset()         { *m = PhoneConfirmResponse{} }
func (m *PhoneConfirmResponse) String() string { return proto.CompactTextString(m) }
func (*PhoneConfirmResponse) ProtoMessage()    {}
func (*PhoneConfirmResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52e9aa8bf733a4d2, []int{1}
}

func (m *PhoneConfirmResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneConfirmResponse.Unmarshal(m, b)
}
func (m *PhoneConfirmResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneConfirmResponse.Marshal(b, m, deterministic)
}
func (m *PhoneConfirmResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneConfirmResponse.Merge(m, src)
}
func (m *PhoneConfirmResponse) XXX_Size() int {
	return xxx_messageInfo_PhoneConfirmResponse.Size(m)
}
func (m *PhoneConfirmResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneConfirmResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneConfirmResponse proto.InternalMessageInfo

func (m *PhoneConfirmResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *PhoneConfirmResponse) GetExtendStatus() string {
	if m != nil {
		return m.ExtendStatus
	}
	return ""
}

func (m *PhoneConfirmResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *PhoneConfirmResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *PhoneConfirmResponse) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func init() {
	proto.RegisterType((*PhoneConfirmRequest)(nil), "proto.PhoneConfirmRequest")
	proto.RegisterType((*PhoneConfirmResponse)(nil), "proto.PhoneConfirmResponse")
}

func init() {
	proto.RegisterFile("service.phone.confirmation.proto", fileDescriptor_52e9aa8bf733a4d2)
}

var fileDescriptor_52e9aa8bf733a4d2 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x15, 0x48, 0x82, 0x38, 0x3a, 0x1d, 0x15, 0xb2, 0xca, 0x12, 0x65, 0x62, 0xca, 0x00,
	0x8f, 0xc0, 0xc0, 0x8a, 0x5a, 0xb1, 0x22, 0xb9, 0xee, 0x41, 0x2d, 0x5c, 0x3b, 0xc4, 0x2e, 0xea,
	0x73, 0xf0, 0x0e, 0xbc, 0x27, 0xb2, 0xaf, 0x55, 0x1d, 0x29, 0x53, 0xee, 0xbe, 0xff, 0xa2, 0xff,
	0xf7, 0x0f, 0x8d, 0xa7, 0xe1, 0x47, 0x2b, 0xea, 0xfa, 0xad, 0xb3, 0xd4, 0x29, 0x67, 0x3f, 0xf4,
	0xb0, 0x93, 0x41, 0x3b, 0xdb, 0xf5, 0x83, 0x0b, 0x0e, 0xab, 0xf4, 0x69, 0xff, 0x0a, 0xb8, 0x7d,
	0x8d, 0x37, 0xcf, 0x7c, 0xb2, 0xa4, 0xef, 0x3d, 0xf9, 0x80, 0x73, 0xa8, 0xd2, 0xaf, 0xa2, 0x68,
	0x8a, 0x87, 0xeb, 0x25, 0x2f, 0x88, 0x50, 0x06, 0x3a, 0x04, 0x71, 0x91, 0x60, 0x9a, 0x23, 0xf3,
	0xfa, 0xd3, 0x8a, 0x4b, 0x66, 0x71, 0x46, 0x01, 0x57, 0x6a, 0x2b, 0xad, 0x25, 0x23, 0xca, 0x84,
	0x4f, 0x2b, 0x36, 0x70, 0xa3, 0xa4, 0x31, 0x6b, 0xa9, 0xbe, 0xde, 0x06, 0x23, 0xaa, 0xa4, 0xe6,
	0x28, 0x3a, 0xd3, 0x4e, 0x6a, 0x23, 0x6a, 0x76, 0x4e, 0x4b, 0xfb, 0x5b, 0xc0, 0x7c, 0x9c, 0xd3,
	0xf7, 0xce, 0x7a, 0xc2, 0x3b, 0xa8, 0x7d, 0x90, 0x61, 0xef, 0x8f, 0x49, 0x8f, 0x1b, 0xb6, 0x30,
	0xa3, 0x43, 0x20, 0xbb, 0x59, 0xb1, 0xca, 0x91, 0x47, 0x2c, 0x46, 0x57, 0x6e, 0x43, 0xa7, 0xe8,
	0x71, 0x3e, 0xdb, 0x97, 0x99, 0xfd, 0xb9, 0x8e, 0x2a, 0xab, 0xe3, 0xf1, 0x7d, 0xdc, 0xdd, 0x8a,
	0x3b, 0xc7, 0x17, 0x98, 0xe5, 0x18, 0x17, 0x5c, 0x79, 0x37, 0xd1, 0xf3, 0xe2, 0x7e, 0x52, 0xe3,
	0xb7, 0xad, 0xeb, 0xa4, 0x3d, 0xfd, 0x07, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x36, 0xa8, 0xb9, 0xce,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PhoneConfirmServiceClient is the client API for PhoneConfirmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PhoneConfirmServiceClient interface {
	PhoneConfirm(ctx context.Context, in *PhoneConfirmRequest, opts ...grpc.CallOption) (*PhoneConfirmResponse, error)
}

type phoneConfirmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPhoneConfirmServiceClient(cc grpc.ClientConnInterface) PhoneConfirmServiceClient {
	return &phoneConfirmServiceClient{cc}
}

func (c *phoneConfirmServiceClient) PhoneConfirm(ctx context.Context, in *PhoneConfirmRequest, opts ...grpc.CallOption) (*PhoneConfirmResponse, error) {
	out := new(PhoneConfirmResponse)
	err := c.cc.Invoke(ctx, "/proto.PhoneConfirmService/PhoneConfirm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PhoneConfirmServiceServer is the server API for PhoneConfirmService service.
type PhoneConfirmServiceServer interface {
	PhoneConfirm(context.Context, *PhoneConfirmRequest) (*PhoneConfirmResponse, error)
}

// UnimplementedPhoneConfirmServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPhoneConfirmServiceServer struct {
}

func (*UnimplementedPhoneConfirmServiceServer) PhoneConfirm(ctx context.Context, req *PhoneConfirmRequest) (*PhoneConfirmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PhoneConfirm not implemented")
}

func RegisterPhoneConfirmServiceServer(s *grpc.Server, srv PhoneConfirmServiceServer) {
	s.RegisterService(&_PhoneConfirmService_serviceDesc, srv)
}

func _PhoneConfirmService_PhoneConfirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhoneConfirmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhoneConfirmServiceServer).PhoneConfirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PhoneConfirmService/PhoneConfirm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhoneConfirmServiceServer).PhoneConfirm(ctx, req.(*PhoneConfirmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PhoneConfirmService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PhoneConfirmService",
	HandlerType: (*PhoneConfirmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PhoneConfirm",
			Handler:    _PhoneConfirmService_PhoneConfirm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.phone.confirmation.proto",
}
