// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.signup.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignUpRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	PersonName           string   `protobuf:"bytes,3,opt,name=PersonName,proto3" json:"PersonName,omitempty"`
	PersonMiddleName     string   `protobuf:"bytes,4,opt,name=PersonMiddleName,proto3" json:"PersonMiddleName,omitempty"`
	PersonLastName       string   `protobuf:"bytes,5,opt,name=PersonLastName,proto3" json:"PersonLastName,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,6,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRequest) Reset()         { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()    {}
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_943d3aadd689144a, []int{0}
}

func (m *SignUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRequest.Unmarshal(m, b)
}
func (m *SignUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRequest.Marshal(b, m, deterministic)
}
func (m *SignUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRequest.Merge(m, src)
}
func (m *SignUpRequest) XXX_Size() int {
	return xxx_messageInfo_SignUpRequest.Size(m)
}
func (m *SignUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRequest proto.InternalMessageInfo

func (m *SignUpRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignUpRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SignUpRequest) GetPersonName() string {
	if m != nil {
		return m.PersonName
	}
	return ""
}

func (m *SignUpRequest) GetPersonMiddleName() string {
	if m != nil {
		return m.PersonMiddleName
	}
	return ""
}

func (m *SignUpRequest) GetPersonLastName() string {
	if m != nil {
		return m.PersonLastName
	}
	return ""
}

func (m *SignUpRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type SignUpResponse struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	PersonName           string   `protobuf:"bytes,2,opt,name=PersonName,proto3" json:"PersonName,omitempty"`
	PersonMiddleName     string   `protobuf:"bytes,3,opt,name=PersonMiddleName,proto3" json:"PersonMiddleName,omitempty"`
	PersonLastName       string   `protobuf:"bytes,4,opt,name=PersonLastName,proto3" json:"PersonLastName,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,5,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Hash                 uint32   `protobuf:"varint,7,opt,name=hash,proto3" json:"hash,omitempty"`
	Status               bool     `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpResponse) Reset()         { *m = SignUpResponse{} }
func (m *SignUpResponse) String() string { return proto.CompactTextString(m) }
func (*SignUpResponse) ProtoMessage()    {}
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_943d3aadd689144a, []int{1}
}

func (m *SignUpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpResponse.Unmarshal(m, b)
}
func (m *SignUpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpResponse.Marshal(b, m, deterministic)
}
func (m *SignUpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpResponse.Merge(m, src)
}
func (m *SignUpResponse) XXX_Size() int {
	return xxx_messageInfo_SignUpResponse.Size(m)
}
func (m *SignUpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpResponse proto.InternalMessageInfo

func (m *SignUpResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignUpResponse) GetPersonName() string {
	if m != nil {
		return m.PersonName
	}
	return ""
}

func (m *SignUpResponse) GetPersonMiddleName() string {
	if m != nil {
		return m.PersonMiddleName
	}
	return ""
}

func (m *SignUpResponse) GetPersonLastName() string {
	if m != nil {
		return m.PersonLastName
	}
	return ""
}

func (m *SignUpResponse) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *SignUpResponse) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SignUpResponse) GetHash() uint32 {
	if m != nil {
		return m.Hash
	}
	return 0
}

func (m *SignUpResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*SignUpRequest)(nil), "proto.SignUpRequest")
	proto.RegisterType((*SignUpResponse)(nil), "proto.SignUpResponse")
}

func init() {
	proto.RegisterFile("service.signup.proto", fileDescriptor_943d3aadd689144a)
}

var fileDescriptor_943d3aadd689144a = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x49, 0x9b, 0xc4, 0x38, 0xd2, 0x22, 0x43, 0x94, 0xa5, 0x07, 0x09, 0x3d, 0x48, 0xf0,
	0x90, 0x83, 0xe2, 0x2b, 0x78, 0xd2, 0x52, 0x52, 0x7c, 0x80, 0xad, 0x19, 0x9a, 0x40, 0x93, 0x8d,
	0x99, 0x44, 0x5f, 0xc0, 0x77, 0xf4, 0x75, 0x84, 0x59, 0x2b, 0x4d, 0x8a, 0x90, 0xd3, 0xee, 0xf7,
	0x9b, 0xef, 0xf0, 0xcd, 0x1f, 0x08, 0x99, 0x9a, 0x8f, 0xe2, 0x8d, 0x12, 0x2e, 0x76, 0x55, 0x57,
	0x27, 0x75, 0x63, 0x5a, 0x83, 0x9e, 0x3c, 0xcb, 0x6f, 0x07, 0x66, 0x9b, 0x62, 0x57, 0xbd, 0xd6,
	0x29, 0xbd, 0x77, 0xc4, 0x2d, 0x86, 0xe0, 0x51, 0xa9, 0x8b, 0xbd, 0x72, 0x22, 0x27, 0x3e, 0x4f,
	0xad, 0xc0, 0x05, 0x04, 0xb5, 0x66, 0xfe, 0x34, 0x4d, 0xa6, 0x26, 0x52, 0xf8, 0xd3, 0x78, 0x03,
	0xb0, 0xa6, 0x86, 0x4d, 0xb5, 0xd2, 0x25, 0xa9, 0xa9, 0x54, 0x8f, 0x08, 0xde, 0xc1, 0xa5, 0x55,
	0x2f, 0x45, 0x96, 0xed, 0x49, 0x5c, 0xae, 0xb8, 0x4e, 0x38, 0xde, 0xc2, 0xdc, 0xb2, 0x67, 0xcd,
	0xad, 0x38, 0x3d, 0x71, 0x0e, 0x28, 0x46, 0x70, 0xb1, 0xce, 0x4d, 0x45, 0xab, 0xae, 0xdc, 0x52,
	0xa3, 0x7c, 0x31, 0x1d, 0xa3, 0xe5, 0xd7, 0x04, 0xe6, 0x87, 0xce, 0xb8, 0x36, 0x15, 0xd3, 0x3f,
	0xad, 0xf5, 0xe3, 0x4f, 0x46, 0xc5, 0x9f, 0x8e, 0x8e, 0xef, 0x8e, 0x89, 0xef, 0x9d, 0xc4, 0xef,
	0x0d, 0xdc, 0x1f, 0x0c, 0x1c, 0xc1, 0xcd, 0x35, 0xe7, 0xea, 0x2c, 0x72, 0xe2, 0x59, 0x2a, 0x7f,
	0xbc, 0x06, 0x9f, 0x5b, 0xdd, 0x76, 0xac, 0x82, 0xc8, 0x89, 0x83, 0xf4, 0x57, 0xdd, 0x3f, 0x1d,
	0xf6, 0xbb, 0xb1, 0x57, 0x80, 0x8f, 0xe0, 0x5b, 0x80, 0xa1, 0x3d, 0x85, 0xa4, 0xb7, 0xff, 0xc5,
	0xd5, 0x80, 0xda, 0xd9, 0x6d, 0x7d, 0xa1, 0x0f, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x9a,
	0x12, 0x48, 0x4e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SignUpServiceClient is the client API for SignUpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SignUpServiceClient interface {
	SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpResponse, error)
}

type signUpServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSignUpServiceClient(cc grpc.ClientConnInterface) SignUpServiceClient {
	return &signUpServiceClient{cc}
}

func (c *signUpServiceClient) SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpResponse, error) {
	out := new(SignUpResponse)
	err := c.cc.Invoke(ctx, "/proto.SignUpService/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignUpServiceServer is the server API for SignUpService service.
type SignUpServiceServer interface {
	SignUp(context.Context, *SignUpRequest) (*SignUpResponse, error)
}

// UnimplementedSignUpServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSignUpServiceServer struct {
}

func (*UnimplementedSignUpServiceServer) SignUp(ctx context.Context, req *SignUpRequest) (*SignUpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}

func RegisterSignUpServiceServer(s *grpc.Server, srv SignUpServiceServer) {
	s.RegisterService(&_SignUpService_serviceDesc, srv)
}

func _SignUpService_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignUpServiceServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SignUpService/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignUpServiceServer).SignUp(ctx, req.(*SignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SignUpService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SignUpService",
	HandlerType: (*SignUpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignUp",
			Handler:    _SignUpService_SignUp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.signup.proto",
}
